on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: R1tschY/sailfish-sdk-action@master
      with:
        arch: 'armv7hl'
        release: '3.3.0.14'
        fix-version: false
    - run: echo rpm-dir ${{ steps.foo.outputs.rpm-dir }} 
      shell: bash
